### ISSUE TITLE
Be careful with GD devices

### ISSUE THREAD

**Issue by Smtsmcloak** [DJPlaya/Tesseract-Cobra#2]
The default download address in the GD DFU tool is 0x08000000. However, the correct starting address for the firmware bin file should be 0x08003000.
Using the default address to download the firmware will brick the device. If the original firmware is not backed beforehand, there will be no way to recover the device due to copy protection.

**Comment by DJPlaya** [comment]
Thanks for contributing, this is definitely important.
Both version show me 0x followed by the default Var Value of 8000000. Is the last Zero cut off? Ime not an Expert, is the correct Var Value 8003000 like so?:
![](https://i.imgur.com/HmjmsiP.png)

**Comment by AnranLee** [comment]
> 

The address is 0x8003000. Sorry for my typo.

**Comment by Smtsmcloak** [comment]
> 

Yes, the zero is cut. The address in your picture is correct.
